### ISSUE TITLE
Error py 3.6

### ISSUE THREAD

**Issue by BUTCHERS228** [mick88/samp-client#13] opened 2020-05-30 15:14 UTC
Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/untitled8/srv.py", line 4, in <module>
    print (client.get_server_clients())
  File "C:\Users\user\PycharmProjects\untitled8\venv\lib\site-packages\samp_client\client.py", line 105, in get_server_clients
    num_clients = decode_int(response[:2])
TypeError: 'NoneType' object is not subscriptable

**Comment by nathanramli** [comment] 2020-07-05 05:33
I have doing some research, not sure if this because the python version.
Probably this because the request doesn't get any response, the response returning None value.

**Comment by mick88** [comment] 2020-09-22 17:58
It looks like Sa-mp server doesn't return a list of users if there's over 100 players online - please see if SA-MP client shows you the list of players for that ip address.

There's not enough information to replicate your issue, so I'm going to close it. Please reopen if you have evidence that the issue is a bug in the samp-client package.

**Closed by mick88** 2020-09-22 17:58 UTC
