### ISSUE TITLE
get_server_clients_detailed()

### ISSUE THREAD

**Issue by tlwsn** [mick88/samp-client#12] opened 2020-02-13 14:13 UTC
when i used get_server_clients_detailed() i got that error:
`Traceback (most recent call last):
  File "c:/Users/admin/Desktop/saadsdasdasdas.py", line 5, in <module>
    info = client.get_server_clients_detailed()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\samp_client\client.py", line 122, in get_server_clients_detailed
    num_clients = decode_int(response[:2])
TypeError: 'NoneType' object is not subscriptable`
how i can fix it?

**Comment by mick88** [comment] 2020-04-22 15:29
I don't think this project will run on Pyton 3.8. Try 3.7 or older

**Comment by tlwsn** [comment] 2020-06-29 16:30
i ran into a problem only when server had too much players played online. I also tried on ~50 players server and all have worked fine

**Comment by nathanramli** [comment] 2020-07-04 13:02
Hello @mick88 
I'm willing to update this library to support python 3.8.

**Comment by mick88** [comment] 2020-09-22 18:02
It looks like Sa-mp server doesn't return a list of users if there's over 100 players online - please see if SA-MP client shows you the list of players for that ip address.

There's not enough information to replicate your issue, so I'm going to close it. Please reopen if you have evidence that the issue is a bug in the samp-client package.

**Closed by mick88** 2020-09-22 18:02 UTC
